-- AlterTable
ALTER TABLE "Mistake" ADD COLUMN "state" TEXT NOT NULL DEFAULT 'new';
ALTER TABLE "Mistake" ADD COLUMN "stability" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "Mistake" ADD COLUMN "difficulty" DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE "Mistake" ADD COLUMN "reps" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Mistake" ADD COLUMN "lapses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Mistake" ADD COLUMN "lastReviewAt" TIMESTAMP(3);
ALTER TABLE "Mistake" ADD COLUMN "nextReviewAt" TIMESTAMP(3);
ALTER TABLE "Mistake" ADD COLUMN "history" JSONB NOT NULL DEFAULT '[]';
CREATE INDEX "Mistake_userId_nextReviewAt_idx" ON "Mistake"("userId", "nextReviewAt");
